version: '3.8'

services:
  passenger-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VITE_API_URL=http://debian
      - DOMAIN_NAME=example.com # Replace with your actual domain name
      - EMAIL=example@email.com # Replace with your email for Let's Encrypt notifications
    volumes:
      - letsencrypt_certs:/etc/letsencrypt # Persistent storage for certificates
      - letsencrypt_lib:/var/lib/letsencrypt
    restart: unless-stopped
    networks:
      - passenger-network

networks:
  passenger-network:
    driver: bridge

volumes:
  letsencrypt_certs:
  letsencrypt_lib:
